#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
ls -l /data
find /data
uv run python -u run_capsule.py "$@"
